{% set name = "pytray" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytray-{{ version }}.tar.gz
  sha256: 1636954425e290fb0051361db95d8ba56b7471abb96510fdcaac049ff540b5c9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - async_generator
    - deprecation
    - python >=3.5

test:
  imports:
    - pytray

about:
  home: https://github.com/muhrin/pytray
  summary: A python tools library for baking pies
  description: |
    A collection of small utility libraries covering things such as pretty printing, using asyncio on a separate thread,
    weakly referencing objects by id in a dictionary and others.  These are things I have found useful across several
    projects I have been involved in including kiwiPy, mincePy, minkiPy, pyOS and you can find usage examples therein.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE


extra:
  recipe-maintainers:
    - muhrin
